### ISSUE TITLE
Update Keybase to version 5.9.0

### ISSUE THREAD

**Issue by GoliathLabs** [facorread/keybase-chocolatey#1]
Hello,
there is a new update available (https://github.com/keybase/client/releases/tag/v5.9.0)

**Comment by GoliathLabs** [comment]
It seems like the package has been updated on the chocolatey repository, yet no commit has been made here @facorread

**Comment by facorread** [comment]
Thanks for pointing that out! I just pushed the commit.

**Comment by GoliathLabs** [comment]
Perfect, much appreciated :)
